sonar.projectKey=hobsojam_simple-estimation
sonar.organization=hobsojam

sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,server/public/**,**/*.test.js,**/*.spec.js,e2e/**
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=reports/server/lcov.info,reports/client/lcov.info
